- name: Install deps
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: download docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Really we just do this for the cache update
  yum:
    name: "*"
    state: latest
    update_cache: true

- name: install docker
  yum:
    name: docker-ce
    state: present

- name: restart service docker
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: docker
